services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - web
      - prometheus
    #ports:
    #  - 9091:9090
    labels:
      - "traefik.enable=true"
      - "traefix.docker.network=web"
      - "traefik.http.routers.prometheus.entryPoints=https"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.nothing2seehere.duckdns.org`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=internal-ipallowlist@file"    
  
  node-exporter:
    image: prom/node-exporter
    container_name: prometheus-exporter
    networks:
      - prometheus
    ports:
      - 9100:9100
#    labels:
#      - "traefik.enable=true"
#      - "traefix.docker.network=web"
#      - "traefik.http.routers.node_exporter.entryPoints=https"
#      - "traefik.http.routers.node_exporter.rule=Host(`node_exporter.nothing2seehere.duckdns.org`)"
#      - "traefik.http.services.node_exporter.loadbalancer.server.port=9100"
#      - "traefik.http.routers.node_exporter.middlewares=internal-ipallowlist@file"

networks:
  web:
    external: true
  prometheus:
    name: prometheus 
