global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets: 
      - prometheus:9090
 - job_name: node
   static_configs:
    - targets:
      - node-exporter:9100
 - job_name: nut-primary
   metrics_path: /ups_metrics
   static_configs:
     - targets: ['nut-exporter:9199']
#       labels:
#         ups:  "3dprinter"
#   params:
#     ups: [ "3dprinter" ]
#     server: [ "nutserver1" ]
